version: '3.8'
services:
  springboot-kotlin-employee-api:
    image: springboot-kotlin-employee-api
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - data:/data/employee-api
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - data:/data
    networks:
      - network-mongo-spring
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin

  mongo-express:
      image: mongo-express
      container_name: mongo-express
      restart: always
      ports:
        - "8081:8081"
      environment:
        - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
        - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
        - ME_CONFIG_MONGODB_SERVER=mongodb

volumes:
  data: {}

networks:
  network-mongo-spring:
