version: '3.8'
services:
  springboot-kotlin-employee-api:
    image: springboot-kotlin-employee-api
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - data:/data/employee-api
    ports:
      - "8080:8080"

volumes:
  data: {}
