logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    de.hexad.restapikotlin: DEBUG

spring:
  data:
    mongodb:
      database: admin
      host: localhost
      username: admin
      password: admin
      port: 27017

#  jpa:
#    hibernate:
#      ddl-auto: update
